export var Data = [
    {
        code: 2005,
        subject: "Mechanics",
        videoCard:false,
        title:"Application of Lami's Theorem, JIB CRANE",
        date:"21/03/2023",
        notes:"https://drive.google.com/file/d/1sezhw154WkFXhFeQIhAdiEyvgvau-9Vi/view?usp=share_link",
        link : "https://www.youtube.com/embed/zDuEl0BXM2w",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Types of Beam, Support and Load",
        date:"25/03/2023",
        notes:"https://drive.google.com/file/d/1ruoIrSpVnivxOjSs7PocYf8R7DBgljOh/view?usp=share_link",
        link : "https://www.youtube.com/embed/R5WmqftXnRs",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Numericals of Chapter 'Beam'",
        date:"28/03/2023",
        notes:"https://drive.google.com/file/d/1pWW-asfbq4DjYi-A45qYAn_gga6ZC1EC/view?usp=share_link",
        link : "https://www.youtube.com/embed/h_8wsYklgxM",
        author:"Sh. Gaurang Sharma",
    },    
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Friction and Law's of Friction",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/1j7ozytz1PBz-UQpfq2SLAUyP2GN6WzUS/view?usp=share_link",
        link : "https://www.youtube.com/embed/kggawNT1yvU",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Limiting Equilibrium and Friction, Coefficient of Friction (µ), Angle of Friction, Relation between Angle of Friction and Coefficient of Friction",
        date:"1/04/2023",
        notes:"https://drive.google.com/file/d/1G8YdgU-Y03XhoUWMSaTUswYQnMnOPPUb/view?usp=share_link",
        link : "https://www.youtube.com/embed/T5R_bbPUk3k",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"Vector",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/115ubigQPTPPppP6urkHvLv5ZTBPg6lxf/view?usp=share_link",
        link : "https://www.youtube.com/embed/WKNk-qRP_5Q",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"Magnetic force on Moving charge and current carrying conductor in Uniform Magnetic field",
        date:"31/03/2023",
        notes:"",
        link : "https://www.youtube.com/embed/n4yVUF4Zp4E",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Inclined Plain",
        date:"13/04/2023",
        notes:"https://drive.google.com/file/d/1t3ovnGAIsiXm7EcnRdtGjYhw7tffr401/view?usp=share_link",
        link : "https://www.youtube.com/embed/mmxHeI43G9c",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 1 & 2",
        date:"15/04/2023",
        notes:"https://drive.google.com/file/d/1PzA3Y5dlN2LYu2ZaCyBBmjGJDgChRieo/view?usp=share_link",
        link : "https://www.youtube.com/embed/N1bzk3inbuY",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 3 & 4",
        date:"18/04/2023",
        notes:"https://drive.google.com/file/d/1lk6OhTJBwFI8M6pvnGnPp2Cc3AEWK7Hc/view?usp=share_link",
        link : "https://www.youtube.com/embed/XofqxMyVjO4",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, C Shape, Z Shape, T Shape, F Shape",
        date:"20/04/2023",
        notes:"",
        link : "https://www.youtube.com/embed/Ff8voYXzqmM",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"Explain formation of P-Type and N-Type Semi-conductor. WHat do you mean by PN Junction diote? Explain it's characteristics curve.",
        date:"21/04/2023",
        notes:"https://drive.google.com/file/d/1Q__qiNg8vMTCKMWFBBxkD4eziJdgyQYZ/view?usp=share_link",
        link : "https://www.youtube.com/embed/cK9wQG8LgiM",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"3D Shapes in Centroid and Center of Gravity.",
        date:"21/04/2023",
        notes:"",
        link : "https://www.youtube.com/embed/Ej5cs0tKeDQ",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"What do you mean by Zener Diote? Explain characteristics curve of zener diode.  What do you mean by Rectifier? Explain working of half wave rectifier. ",
        date:"24/04/2023",
        notes:"https://drive.google.com/file/d/1JxgvgxTeV659dTcS9HRxS7aWyadIRZ8X/view?usp=share_link",
        link : "https://www.youtube.com/embed/NG6VKPqpnhM",
        author:"Sh. Hemant Salvi",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/fHTEpQ7UbiU",
        title:"Cramer's Rule",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/cUFlioM6mgk",
        title:"Inverse of a Matrix",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/ZY2jycIl0Zg",
        title:"Determinants Full Chapter",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/R4s2vzJeBPI",
        title:"VECTOR ALGEBRA",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/-yky85p3Yg8",
        title:"समाकलन INTEGRATION Part 1",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/m-ve2pSXPmw",
        title:"समाकलन INTEGRATION Part 2",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/xyd98qN15bE",
        title:"समाकलन INTEGRATION Part 3",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/EStNFduCn8o",
        title:"समाकलन INTEGRATION Part 4",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/vDVs_CXplEg",
        title:"समाकलन INTEGRATION Part 5",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/0rNAZao2iVI",
        title:"Matrix Part 1",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/1_WrsYnG5eY",
        title:"Matrix Part 2",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/AR3JwKr5Kp8",
        title:"Matrix Part 3",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        link:"https://youtu.be/OwWBnP86vV0",
        title:"Matrix Part 4",
    },
    {
        code: 2005,
        videoCard:false,
        notification: true,
        subject: "Mechanics",
        title:"The Height of a Uniform Frustum of a cone is 28cm and the radius of it top and bottom are 21cm and 35cm Respectively find the distance of its C.G. from the base of the cone.",
        date:"25/04/2023",
        notes:"",
        link : "https://www.youtube.com/embed/ODbLBFyxBiw",
        author:"Sh. Gaurang Sharma",
    },
    
    // {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/_Bc9abfywLw",
    //     author:"Sh. Gaurang Sharma",
    // }, {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/l2l6BY2EtMM",
    //     author:"Sh. Gaurang Sharma",
    // },
    // {
    //     code:2001,
    //     subject: "Maths",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link:"https://www.youtube-nocookie.com/embed/gL_LIAm22Mc",
    //     author:"Mrs Sneha Kothari",
    // },
]

