export var Data = [
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"Vector",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/115ubigQPTPPppP6urkHvLv5ZTBPg6lxf/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/WKNk-qRP_5Q",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"Integration Excercise I(A)-I(B) ",
        date:"26/04/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/DVvV3V4XMvc",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"Integration by Parts and Second semester previous year Question Paper.",
        date:"28/04/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/bQHlikZucNg",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"Integration by Parts",
        date:"03/05/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/lVEEUtlr5qU",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2001,
        videoCard:false,
        subject: "Maths",
        title:"| 2022 Exam questions of Intergrals || Diffrential Equation Method || Unit-4 Coordinate Geometry |  ",
        date:"05/05/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/1c-4C54ycOM",
        author:"Dr. Sneha Kothari",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/fHTEpQ7UbiU",
        title:"Cramer's Rule",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/cUFlioM6mgk",
        title:"Inverse of a Matrix",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/ZY2jycIl0Zg",
        title:"Determinants Full Chapter",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/R4s2vzJeBPI",
        title:"VECTOR ALGEBRA",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/-yky85p3Yg8",
        title:"समाकलन INTEGRATION Part 1",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/m-ve2pSXPmw",
        title:"समाकलन INTEGRATION Part 2",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/xyd98qN15bE",
        title:"समाकलन INTEGRATION Part 3",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/EStNFduCn8o",
        title:"समाकलन INTEGRATION Part 4",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/vDVs_CXplEg",
        title:"समाकलन INTEGRATION Part 5",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/0rNAZao2iVI",
        title:"Matrix Part 1",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/1_WrsYnG5eY",
        title:"Matrix Part 2",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/AR3JwKr5Kp8",
        title:"Matrix Part 3",
    },
    {
        code:2001,
        subject:"Maths",
        author:"Sh. Amit Kushwaha",
        videoCard:true,
        videoLink:"https://youtu.be/OwWBnP86vV0",
        title:"Matrix Part 4",
    },
    {
        code: 2005,
        subject: "Mechanics",
        videoCard:false,
        title:"Application of Lami's Theorem, JIB CRANE",
        date:"21/03/2023",
        notes:"https://drive.google.com/file/d/1sezhw154WkFXhFeQIhAdiEyvgvau-9Vi/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/zDuEl0BXM2w",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Types of Beam, Support and Load",
        date:"25/03/2023",
        notes:"https://drive.google.com/file/d/1ruoIrSpVnivxOjSs7PocYf8R7DBgljOh/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/R5WmqftXnRs",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Numericals of Chapter 'Beam'",
        date:"28/03/2023",
        notes:"https://drive.google.com/file/d/1pWW-asfbq4DjYi-A45qYAn_gga6ZC1EC/view?usp=share_link",
        videoLink: "https://www.youtube.com/embed/h_8wsYklgxM",
        author:"Sh. Gaurang Sharma",
    },    
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Friction and Law's of Friction",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/1j7ozytz1PBz-UQpfq2SLAUyP2GN6WzUS/view?usp=share_link",
        videoLink: "https://www.youtube.com/embed/kggawNT1yvU",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Limiting Equilibrium and Friction, Coefficient of Friction (µ), Angle of Friction, Relation between Angle of Friction and Coefficient of Friction",
        date:"1/04/2023",
        notes:"https://drive.google.com/file/d/1G8YdgU-Y03XhoUWMSaTUswYQnMnOPPUb/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/T5R_bbPUk3k",
        author:"Sh. Gaurang Sharma",
    },

    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"Magnetic force on Moving charge and current carrying conductor in Uniform Magnetic field",
        date:"31/03/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/n4yVUF4Zp4E",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Inclined Plain",
        date:"13/04/2023",
        notes:"https://drive.google.com/file/d/1t3ovnGAIsiXm7EcnRdtGjYhw7tffr401/view?usp=share_link",
        videoLink: "https://www.youtube.com/embed/mmxHeI43G9c",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 1 & 2",
        date:"15/04/2023",
        notes:"https://drive.google.com/file/d/1PzA3Y5dlN2LYu2ZaCyBBmjGJDgChRieo/view?usp=share_link",
        videoLink: "https://www.youtube.com/embed/N1bzk3inbuY",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 3 & 4",
        date:"18/04/2023",
        notes:"https://drive.google.com/file/d/1lk6OhTJBwFI8M6pvnGnPp2Cc3AEWK7Hc/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/XofqxMyVjO4",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, C Shape, Z Shape, T Shape, F Shape",
        date:"20/04/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/Ff8voYXzqmM",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"Explain formation of P-Type and N-Type Semi-conductor. WHat do you mean by PN Junction diote? Explain it's characteristics curve.",
        date:"21/04/2023",
        notes:"https://drive.google.com/file/d/1Q__qiNg8vMTCKMWFBBxkD4eziJdgyQYZ/view?usp=share_link",
        videoLink: "https://www.youtube.com/embed/cK9wQG8LgiM",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"3D Shapes in Centroid and Center of Gravity.",
        date:"21/04/2023",
        notes:"",
        videoLink : "https://www.youtube.com/embed/Ej5cs0tKeDQ",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"What do you mean by Zener Diote? Explain characteristics curve of zener diode.  What do you mean by Rectifier? Explain working of half wave rectifier. ",
        date:"24/04/2023",
        notes:"https://drive.google.com/file/d/1JxgvgxTeV659dTcS9HRxS7aWyadIRZ8X/view?usp=share_link",
        videoLink : "https://www.youtube.com/embed/NG6VKPqpnhM",
        author:"Sh. Hemant Salvi",
    },
    
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"The Height of a Uniform Frustum of a cone is 28cm and the radius of it top and bottom are 21cm and 35cm Respectively find the distance of its C.G. from the base of the cone.",
        date:"25/04/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/ODbLBFyxBiw",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"What do you mean by Full wave Rectifier. Explain Working, Use and Construction of Full wave Rectifier. What do you mean by LASER light. Write Special features of LASER light. ",
        date:"25/04/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/5r-m3kBBVEc",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"(End of Unit-4 'Center of Gravity') (Starting of Unit-5 'Simple Machine') Two uniform spheres composed of the same material and who's diameter's are 6cm and 12cm are touching each other. Find the position of the C.G. of the two sphere's taken together. ",
        date:"27/04/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/e56y_Dc1qqY",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"Simple Machine - 'Velocity Ratio', 'Efficiency', 'Ideal Machine', 'Friction in Machine [Actual Machine]'",
        date:"28/04/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/_MQE75XsPpc",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"| Effort lost due to friction and Load lost due to friction. |  Maximum Efficiancy and Maximum Mechanical Advantage. | Law of Machine. | Numeriacal",
        date:"02/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/zZZRgkH9HkQ",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"Explain Helium Neon Laser.",
        date:"02/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/RfZi5tG6Aq0",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"| A Lifiting machine lifts 770 newton weight by 15 newton effort. If efficiency at this load is 60% then find the velocity ratio. Now find efficiency at 25 newton effort and 1320 newton load also find Maximum Efficiency of Machine. || A Machine of Velocity Ratio 30, lift's 200 newton and 400 newton with efforts 20 newton and 24 newton respectively. (A) Find Law of Machine. (B) Find Effort to lift 300 newton. (C) Find Efficiency. (D) Find Efforst lost in Friction. |",
        date:"04/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/rKsb9phPJAE",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"| Optics || What do you mean by Light || Basic Law of Optics || Reflection and Law of Reflection || Refraction and Law of Refraction ||   ",
        date:"03/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/MJdGpdxt8LU",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"| Explain Critical Error. || Explain Total internal Reflection and Optical Fiber Cable. |",
        date:"05/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/noA1D501VqE",
        author:"Sh. Hemant Salvi",
    },
     {
        code: 2005,
        videoCard:false,
        subject: "Mechanics",
        title:"| In a Lifting Machine Velocity Ratio is 15. A load of 900 Newton can be lifted with an Effort of 150 Newton. Find out the Efficiency of machine, Loss in effort and Load due to friction. || In a lifting machine an effort of 100 Newton was required to lift a load of 3000 Newton. The Velocity Ratio of machine being 40. Is the machine reversible? | ",
        date:"06/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/jvQ-3LJpi0I",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        videoCard:false,
        subject: "Physics",
        title:"| Difference between Convex and Concave lense. || Focal length of convex lense is 10cm and distance of object from lense is 20cm. Find out position and nature of image. || Explain the Ray diagram of microscope also explain magnification of microscope. | ",
        date:"08/05/2023",
        notes:"",
        videoLink: "https://www.youtube.com/embed/MkBMDL-UzFU",
        author:"Sh. Hemant Salvi",
    },
    // {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/_Bc9abfywLw",
    //     author:"Sh. Gaurang Sharma",
    // }, {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/l2l6BY2EtMM",
    //     author:"Sh. Gaurang Sharma",
    // },
    // {
    //     code:2001,
    //     subject: "Maths",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link:"https://www.youtube-nocookie.com/embed/gL_LIAm22Mc",
    //     author:"Mrs Sneha Kothari",
    // },
]

