export var Data = [
    {
        code: 2005,
        subject: "Mechanics",
        title:"Application of Lami's Theorem, JIB CRANE",
        date:"21/03/2023",
        notes:"https://drive.google.com/file/d/1sezhw154WkFXhFeQIhAdiEyvgvau-9Vi/view?usp=share_link",
        link : "https://www.youtube.com/embed/zDuEl0BXM2w",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Types of Beam, Support and Load",
        date:"25/03/2023",
        notes:"https://drive.google.com/file/d/1ruoIrSpVnivxOjSs7PocYf8R7DBgljOh/view?usp=share_link",
        link : "https://www.youtube.com/embed/R5WmqftXnRs",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Numericals of Chapter 'Beam'",
        date:"28/03/2023",
        notes:"https://drive.google.com/file/d/1pWW-asfbq4DjYi-A45qYAn_gga6ZC1EC/view?usp=share_link",
        link : "https://www.youtube.com/embed/h_8wsYklgxM",
        author:"Sh. Gaurang Sharma",
    },    
    {
        code: 2005,
        subject: "Mechanics",
        title:"Friction and Law's of Friction",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/1j7ozytz1PBz-UQpfq2SLAUyP2GN6WzUS/view?usp=share_link",
        link : "https://www.youtube.com/embed/kggawNT1yvU",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Limiting Equilibrium and Friction, Coefficient of Friction (µ), Angle of Friction, Relation between Angle of Friction and Coefficient of Friction",
        date:"1/04/2023",
        notes:"https://drive.google.com/file/d/1G8YdgU-Y03XhoUWMSaTUswYQnMnOPPUb/view?usp=share_link",
        link : "https://www.youtube.com/embed/T5R_bbPUk3k",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2001,
        subject: "Maths",
        title:"Vector",
        date:"31/03/2023",
        notes:"https://drive.google.com/file/d/115ubigQPTPPppP6urkHvLv5ZTBPg6lxf/view?usp=share_link",
        link : "https://www.youtube.com/embed/WKNk-qRP_5Q",
        author:"Dr. Sneha Kothari",
    },
    {
        code: 2002,
        subject: "Physics",
        title:"Magnetic force on Moving charge and current carrying conductor in Uniform Magnetic field",
        date:"31/03/2023",
        notes:"",
        link : "https://www.youtube.com/embed/n4yVUF4Zp4E",
        author:"Sh. Hemant Salvi",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Inclined Plain",
        date:"13/04/2023",
        notes:"https://drive.google.com/file/d/1t3ovnGAIsiXm7EcnRdtGjYhw7tffr401/view?usp=share_link",
        link : "https://www.youtube.com/embed/mmxHeI43G9c",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 1 & 2",
        date:"15/04/2023",
        notes:"https://drive.google.com/file/d/1PzA3Y5dlN2LYu2ZaCyBBmjGJDgChRieo/view?usp=share_link",
        link : "https://www.youtube.com/embed/N1bzk3inbuY",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, Step 3 & 4",
        date:"18/04/2023",
        notes:"https://drive.google.com/file/d/1lk6OhTJBwFI8M6pvnGnPp2Cc3AEWK7Hc/view?usp=share_link",
        link : "https://www.youtube.com/embed/XofqxMyVjO4",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2005,
        subject: "Mechanics",
        title:"Centroid and Center of Gravity, C Shape, Z Shape, T Shape, F Shape",
        date:"20/04/2023",
        notes:"",
        link : "https://www.youtube.com/embed/Ff8voYXzqmM",
        author:"Sh. Gaurang Sharma",
    },
    {
        code: 2002,
        subject: "Physics",
        title:"Explain formation of P-Type and N-Type Semi-conductor. WHat do you mean by PN Junction diote? Explain it's characteristics curve.",
        date:"21/04/2023",
        notes:"",
        link : "https://www.youtube.com/embed/cK9wQG8LgiM",
        author:"Sh. Hemant Salvi",
    },
    

    
    // {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/_Bc9abfywLw",
    //     author:"Sh. Gaurang Sharma",
    // }, {
    //     code: 2005,
    //     subject: "Mechanics",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link : "https://www.youtube-nocookie.com/embed/l2l6BY2EtMM",
    //     author:"Sh. Gaurang Sharma",
    // },
    // {
    //     code:2001,
    //     subject: "Maths",
    //     title:"Application of Lami's Theorem",
    //     date:"21/04/2023",
    //     link:"https://www.youtube-nocookie.com/embed/gL_LIAm22Mc",
    //     author:"Mrs Sneha Kothari",
    // },
]

