const Data = [
  {
    question: "This is question one",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question two",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question three",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question four",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question five",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question five",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question six",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question seven",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question eight",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question nine",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
  {
    question: "This is question ten",
    optionA: "option A",
    optionB: "option B",
    optionC: "option C",
    optionD: "option D",
    correctAns: "option A",
  },
];

export default Data;
