export const Tutorials = [
    {
        subjectCode:2001,
        subject:"Maths",
        details:"First Tutorial",
        teacher:"Dr. Sneha Kothari",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1LR7YE_ehoX4EJbTAcqapRqx4Vhkwsupk/view?usp=share_link",
    },
    {
        subjectCode:2001,
        subject:"Maths",
        details:"Second Tutorial",
        teacher:"Dr. Sneha Kothari",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1YPvWTe85tSc_wXp5ozItLhSJ4kTL5OCW/view?usp=share_link",
    },
    {
        subjectCode:2005,
        subject:"Mechanics",
        details:"First Tutorial",
        teacher:"Sh. Gaurang Sharma",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/13i0LGIfBlG3sqy6gw4ST2uMZb1PuEEQc/view?usp=share_link",
    },
    {
        subjectCode:2005,
        subject:"Mechanics",
        details:"Second Tutorial",
        teacher:"Sh. Gaurang Sharma",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1eZ72ZNS1sz0qyYOU55IPqTTiF1b2kzTq/view?usp=share_link",
    },
    {
        subjectCode:2005,
        subject:"Mechanics",
        details:"Third Tutorial",
        teacher:"Sh. Gaurang Sharma",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1z1J-XQV-9WBbV9CobgDObJDFbEfLqo_p/view?usp=share_link",
    },
    {
        subjectCode:2005,
        subject:"Mechanics",
        details:"Fourth Tutorial",
        teacher:"Sh. Gaurang Sharma",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1Kl9SYtC0N8-waKCC3QzprfX7VUItUM_M/view?usp=share_link",
    },
    {
        subjectCode:2001,
        subject:"Maths",
        details:"Third Tutorial",
        teacher:"Dr. Sneha Kothari",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1fQfOBtq8H9lsSoclDbPGJh14cDlCbYba/view?usp=share_link",
    },
    {
        subjectCode:2001,
        subject:"Maths",
        details:"Fourth Tutorial",
        teacher:"Dr. Sneha Kothari",
        year:"2022-23",
        class:"1st Year",
        semester:"seconde semester",
        link:"https://drive.google.com/file/d/1L8NiQZFNMaxMd861dwsJE6KakB5ClGyh/view?usp=share_link",
    },
]